dist: trusty

language: go

go:
    - 1.8.x
    - tip

before_script:
  - echo $HOSTNAME
  - mkdir -p $GOPATH/bin
  - wget --version
  - wget https://releases.hashicorp.com/consul/0.8.0/consul_0.8.0_linux_amd64.zip
  - wget https://releases.hashicorp.com/vault/0.6.4/vault_0.6.4_linux_amd64.zip
  - unzip -d $GOPATH/bin consul_0.8.0_linux_amd64.zip
  - unzip -d $GOPATH/bin vault_0.6.4_linux_amd64.zip
  - vault --version
  - consul --version
